### PR TITLE
Subreport clean

### PR DESCRIPTION
**Pull request by lysodesigns**
Cleaned up subreport header and added labels to graph

### CODE REVIEW

**Comment by johnnyoshika** [comment]
Reassigned to @LoganHollins

**Comment by johnnyoshika** [comment]
@lysodesigns: I'm not a big fan of red.  It's hard to know which texts are links and which ones aren't:

image

**Comment by johnnyoshika** [comment]
@lysodesigns Any chance you can make this quick fix soon?  Thanks!

**Comment by lysodesigns** [comment]
@johnnyoshika Let me know what you think about the blue

**Comment by johnnyoshika** [comment]
@lysodesigns Much better.  @LoganHollins, if you're happy with it, it's ready to merge.

**Pull request merged**
